### ISSUE TITLE
Outdated examples and dangerous design choices

### ISSUE THREAD

**Issue by Lauler** [KlausVigo/kknn#18]
In your documentation for the `kknn` function you have some outdated examples which seem to be based on an older version of your package. 

```
data(ionosphere)
ionosphere.learn <- ionosphere[1:200,]
ionosphere.valid <- ionosphere[-c(1:200),]
fit.kknn <- kknn(class ~ ., ionosphere.learn, ionosphere.valid)
table(ionosphere.valid$class, fit.kknn$fit)
(fit.train1 <- train.kknn(class ~ ., ionosphere.learn, kmax = 15, 
	kernel = c("triangular", "rectangular", "epanechnikov", "optimal"), distance = 1))
table(predict(fit.train1, ionosphere.valid), ionosphere.valid$class)
(fit.train2 <- train.kknn(class ~ ., ionosphere.learn, kmax = 15, 
	kernel = c("triangular", "rectangular", "epanechnikov", "optimal"), distance = 2))
table(predict(fit.train2, ionosphere.valid), ionosphere.valid$class)
```

For `fit.train1` and `fit.train2`, there is no `test` argument used. Perhaps the fact that they are in parentheses should somehow tip the user off they are not to be used? I do not think those examples should be there at all. 

Another dangerous aspect of the function's documentation is that it gives the impression that the `predict()` method for `kknn` can be used for predictions of new data. It gives the impression that `kknn` follows the conventions of almost every other package, where `newdata` can be supplied as an argument to the `predict()` function in order to make predictions on test data. 

However, that is not the case with `kknn`. And I rather think you should warn users of your package about this in the documentation for `kknn()`. Users will expect `predict.kknn` to work similar to the predict methods of most other packages and may not notice that it will always give you predictions for the `test` set you supplied when fitting the model in `kknn()`. 

I know these distinctions may be crystal clear to you as the designer/maintainer of the package. But I'm currently in a machine learning class, and a significant portion of the class failed to understand that your predict method cannot output predictions on any other data than the `test` set that was already supplied. 

Thanks for developing the package! This was a bit of feedback to guard against user error.

**Comment by kenahoo** [comment]
@Lauler - the syntax `(x <- y)` is often used to make an assignment and also print out the result.  `x <- y` without the parens typically is silent.
