### ISSUE TITLE
Citation link does not work anymore.

### ISSUE THREAD

**Issue by kunkas** [KlausVigo/kknn#20]
The link for the citation below does not work anymore:

Hechenbichler K. and Schliep K.P. (2004) Weighted k-Nearest-Neighbor Techniques and Ordinal Classification, Discussion Paper 399, SFB 386, Ludwig-Maximilians University Munich

**Comment by KlausVigo** [comment]
Hi @kunkas , 
thanks for letting me know. There is a copy of the document coming with kknn. 
I will try to link it to there and / or make it a proper vignette. 
Kind regards, 
Klaus
