### ISSUE TITLE
specClust error

### ISSUE THREAD

**Issue by boyzhirui** [KlausVigo/kknn#4]
When I use the specClust function to do the spectral clustering for a matrix (9482*42), it always gives me the following error:

``` R
Error: C stack usage  7972064 is too close to the limit.
```

I check the stackoverflow website and then increase the C stack usage. [error-c-stack-usage-is-too-close-to-the-limit](http://stackoverflow.com/questions/14719349/error-c-stack-usage-is-too-close-to-the-limit)

After that, I re-run the specClust, I got another error:

``` R
Error: evaluation nested too deeply: infinite recursion / options(expressions=)?
```

I tried to set the nn parameter of the specClust() from 7 to 12, those errors still occurred. The running environment is AWS Ubuntu m4.2xlarge instance(8 CPUs, 32 Gb Memory).

**Comment by KlausVigo** [comment]
@boyzhirui I have to confess I newer saw this error before. Maybe you can try to set the nn to a higher value 50 or 100 and  set gmax also to a positive value ( e.g. 20). 
Can you send me (privately) your data set or a reproducible example? I am just guessing where the error occurs, but this could avoid this problem. 
Thanks, 
Klaus

**Comment by boyzhirui** [comment]
@KlausVigo I've tried the parameter you suggested, but the same error still came out. I've sent you a similar dataset which could produce the error. 
Thanks,
Rui

**Comment by boyzhirui** [comment]
@KlausVigo I run the same code on my Mac Pro, it works well. The R version on my Mac is 3.3.1 (2016-06-21).  kknn version is 1.3.1.  I re-install the newest R on the instance and the package works well. Thank you for your help.
