### ISSUE TITLE
[Bug] `kknn` computes incorrect neighbours for k >= train_size - 1

### ISSUE THREAD

**Issue by RomeroBarata** [KlausVigo/kknn#9]
Here is a reproducible example:

    set.seed(126)
    a <- data.frame(a = rnorm(5), b = rnorm(5), c = c("X0", "X0", "X0", "X1", "X1"))
    r <- kknn::kknn(c ~ ., train = a, test = a, k = 4, kernel = "rectangular")
    r$C  # The neighbours of the 3rd example are (3, 5, 2, 3), however the last 
         # 3 neighbours should be from (1, 2, 4, 5)

For `k = 5`, which is supposed to work fine since `train` has 5 examples, the algorithm goes haywire and computes some crazy indices. For `k >= 6` I would expect the code to fail but it still runs (and returns some random indices).

**Comment by KlausVigo** [comment]
Hi @RomeroBarata, I fixed a bug which seemed to have caused problems for k==train_size and catch k >train_size. Thanks again for the report.
